# Dockerfile.frontend
FROM node:18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY frontend/package*.json ./
RUN npm install

# Bundle app source
COPY frontend .

# Build Next.js app
RUN npm run build

# Expose the port the app runs on
EXPOSE 3000

# Start the app
CMD ["npm", "start"]